export type Lang = "EN" | "PL" | "ES" | "DE";

interface Dict {
  // nav
  navHome: string;
  navMission: string;
  // hero
  heroLine1: string;
  heroLine2: string;
  heroSub: string;
  comingToMobile: string;
  comingSoon: string;
  verseOfDay: string;
  commonQuestionsLabel: string;
  tryItNow: string;
  buyMeCoffeeText: string;
  buyMeCoffeeBtn: string;
  // preview
  previewTagline: string;
  previewReady: string;
  previewHint: string;
  previewCta: string;
  previewPlaceholder: string;
  // chat
  chatHint: string;
  chatPlaceholder: string;
  responseMode: string;
  modeSimple: string;
  modeDetailed: string;
  modeChallenge: string;
  modeSimpleDesc: string;
  modeDetailedDesc: string;
  modeChallengeDesc: string;
  clearBtn: string;
  printBtn: string;
  errorMsg: string;
  // bubble
  saveBtn: string;
  copyBtn: string;
  copiedBtn: string;
  // about
  aboutTitle: string;
  aboutP1: string;
  aboutP2: string;
  feature1Icon: string;
  feature1Title: string;
  feature1Body: string;
  feature2Icon: string;
  feature2Title: string;
  feature2Body: string;
  feature3Icon: string;
  feature3Title: string;
  feature3Body: string;
  aboutQuote: string;
  aboutQuoteRef: string;
  // print
  printHeader: string;
  printYou: string;
  printBot: string;
  printFooter: string;
  // daily reading
  navDailyReading: string;
  dailyReadingTitle: string;
  dailyReadingLoading: string;
  dailyReadingError: string;
  dailyReadingSource: string;
  // common questions section
  navCommonQuestions: string;
  commonQuestionsTitle: string;
  commonQuestionsSub: string;
  // arrays
  bullets: string[];
  objections: string[];
  starterQuestions: string[];
}

const EN: Dict = {
  navHome: "Home",
  navMission: "Our Mission",
  heroLine1: "The Undefeated",
  heroLine2: "Christian Apologist",
  heroSub: "An AI assistant trained in Scripture, Church history, and comparative religion. Defend your faith, debunk objections, and explore the truth.",
  comingToMobile: "Coming to mobile",
  comingSoon: "Coming Soon",
  verseOfDay: "Verse of the Day",
  commonQuestionsLabel: "Common Questions",
  tryItNow: "Try it now →",
  buyMeCoffeeText: "If you'd like this project to continue and grow, feel free to buy me a coffee — I'm a one-man squad.",
  buyMeCoffeeBtn: "Buy me a coffee ☕",
  previewTagline: "Apologetics AI — Truth stands undefeated",
  previewReady: "Ready",
  previewHint: "Ask anything about Christianity — doctrine, objections, other religions, Biblical questions.",
  previewCta: "Click to start a conversation",
  previewPlaceholder: "Click to start chatting...",
  chatHint: "Ask anything about Christianity — doctrine, objections, other religions, Biblical questions.",
  chatPlaceholder: "Ask about Christianity, objections, or other religions...",
  responseMode: "Response mode:",
  modeSimple: "Simple",
  modeDetailed: "Detailed",
  modeChallenge: "⚔ Challenge",
  modeSimpleDesc: "Short, plain language answers",
  modeDetailedDesc: "In-depth with sources & rebuttals",
  modeChallengeDesc: "Face a skeptic — sharpen your faith",
  clearBtn: "Clear",
  printBtn: "Print",
  errorMsg: "Sorry, something went wrong. Please check your API key and try again.",
  saveBtn: "Save",
  copyBtn: "Copy",
  copiedBtn: "Copied!",
  aboutTitle: "Our Mission",
  aboutP1: "Apologist AI is a free ministry built to equip believers with sound, scripture-grounded answers to the hardest questions about Christianity. Whether you face doubts, skeptics, or sincere questions about the faith, this tool gives you access to centuries of apologetics, church history, and biblical scholarship — in plain language, at any hour.",
  aboutP2: "This is a passion project — one I always felt I had to build, as I genuinely love debating and deepening my knowledge of the faith. I believe every Christian should be able to give a reason for the hope within them (1 Peter 3:15). Not just pastors and scholars — every believer, every day. This project is offered freely, for the glory of Christ.",
  feature1Icon: "📖",
  feature1Title: "Scripture-First",
  feature1Body: "Every answer is grounded in the Word of God, with direct verse references.",
  feature2Icon: "🏛",
  feature2Title: "Historically Rooted",
  feature2Body: "Draws from Church Fathers, reformed theology, and 2,000 years of Christian thought.",
  feature3Icon: "⚔",
  feature3Title: "Battle-Tested",
  feature3Body: "Tackles Islam, atheism, cults, and modern skepticism head-on — confidently and charitably.",
  aboutQuote: "The light shines in the darkness, and the darkness has not overcome it.",
  aboutQuoteRef: "— John 1:5",
  printHeader: "✝ Apologist AI — Conversation",
  printYou: "You",
  printBot: "Apologist AI",
  printFooter: "Generated by ApologistAI.com — For the glory of Christ",
  navDailyReading: "Daily Reading",
  dailyReadingTitle: "Daily Mass Readings",
  dailyReadingLoading: "Loading today's readings…",
  dailyReadingError: "Could not load today's readings. Visit universalis.com for the full text.",
  dailyReadingSource: "Source: Universalis",
  navCommonQuestions: "Common Questions",
  commonQuestionsTitle: "Common Questions",
  commonQuestionsSub: "Tap any question for an instant answer from the AI.",
  bullets: [
    "Defend Christianity with Scripture & logic",
    "Debunk alleged contradictions",
    "Analyze flaws in Islam, atheism & more",
    "Scholar & ministry sources built in",
  ],
  objections: [
    "Does God exist?",
    "Is the Bible reliable?",
    "How do you explain the Trinity?",
    "What about evolution?",
    "How can a good God allow suffering?",
    "What about Biblical contradictions?",
    "Is Islam a better religion?",
    "Did Jesus really rise from the dead?",
  ],
  starterQuestions: [
    "Is the Bible historically reliable?",
    "Does Islam disprove Christianity?",
    "How do you explain the Trinity?",
    "What about Biblical contradictions?",
  ],
};

const PL: Dict = {
  navHome: "Strona główna",
  navMission: "Nasza misja",
  heroLine1: "Niezwyciężona",
  heroLine2: "Apologetyka Chrześcijańska",
  heroSub: "Asystent AI wyszkolony w Piśmie Świętym, historii Kościoła i religioznawstwie. Broń wiary, obalaj zarzuty i odkrywaj prawdę.",
  comingToMobile: "Wkrótce na telefon",
  comingSoon: "Wkrótce",
  verseOfDay: "Werset dnia",
  commonQuestionsLabel: "Częste pytania",
  tryItNow: "Wypróbuj →",
  buyMeCoffeeText: "Jeśli chcesz, żeby ten projekt się rozwijał, postaw mi kawę — jestem tu sam.",
  buyMeCoffeeBtn: "Postaw mi kawę ☕",
  previewTagline: "AI Apologetyczne — Prawda jest niezwyciężona",
  previewReady: "Gotowy",
  previewHint: "Zadaj pytanie o chrześcijaństwo — doktrynę, zarzuty, inne religie, pytania biblijne.",
  previewCta: "Kliknij, aby rozpocząć rozmowę",
  previewPlaceholder: "Kliknij, aby zacząć...",
  chatHint: "Zadaj pytanie o chrześcijaństwo — doktrynę, zarzuty, inne religie, pytania biblijne.",
  chatPlaceholder: "Zadaj pytanie o chrześcijaństwo, zarzuty lub inne religie...",
  responseMode: "Tryb odpowiedzi:",
  modeSimple: "Prosty",
  modeDetailed: "Szczegółowy",
  modeChallenge: "⚔ Wyzwanie",
  modeSimpleDesc: "Krótkie, przystępne odpowiedzi",
  modeDetailedDesc: "Szczegółowe ze źródłami i kontrargumentami",
  modeChallengeDesc: "Stań naprzeciw sceptyka — wzmocnij wiarę",
  clearBtn: "Wyczyść",
  printBtn: "Drukuj",
  errorMsg: "Przepraszamy, coś poszło nie tak. Sprawdź klucz API i spróbuj ponownie.",
  saveBtn: "Zapisz",
  copyBtn: "Kopiuj",
  copiedBtn: "Skopiowano!",
  aboutTitle: "Nasza misja",
  aboutP1: "Apologist AI to bezpłatna posługa zbudowana, aby wyposażyć wierzących w rzetelne, zakorzenione w Piśmie Świętym odpowiedzi na najtrudniejsze pytania dotyczące chrześcijaństwa. Niezależnie od tego, czy mierzysz się z wątpliwościami, sceptykami czy szczerymi pytaniami o wiarę — to narzędzie daje ci dostęp do wieków apologetyki, historii Kościoła i biblistyki — w przystępnym języku, o każdej porze.",
  aboutP2: "To jest projekt z pasji — taki, który zawsze czułem, że muszę zbudować, bo naprawdę lubię debatować i pogłębiać swoją wiedzę o wierze. Uważam, że każdy chrześcijanin powinien być w stanie uzasadnić nadzieję, która w nim jest (1 Piotra 3:15). Nie tylko pastorzy i uczeni — każdy wierzący, każdego dnia. Ten projekt jest oferowany bezpłatnie, dla chwały Chrystusa.",
  feature1Icon: "📖",
  feature1Title: "Biblia na pierwszym miejscu",
  feature1Body: "Każda odpowiedź zakorzeniona jest w Słowie Bożym, z bezpośrednimi odniesieniami do wersetów.",
  feature2Icon: "🏛",
  feature2Title: "Zakorzenione historycznie",
  feature2Body: "Czerpie od Ojców Kościoła, teologii reformowanej i 2000 lat myśli chrześcijańskiej.",
  feature3Icon: "⚔",
  feature3Title: "Sprawdzone w boju",
  feature3Body: "Mierzy się z islamem, ateizmem, kultami i nowoczesnym sceptycyzmem — pewnie i życzliwie.",
  aboutQuote: "Światłość świeci w ciemności, a ciemność jej nie przemogła.",
  aboutQuoteRef: "— Jana 1:5",
  printHeader: "✝ Apologist AI — Rozmowa",
  printYou: "Ty",
  printBot: "Apologist AI",
  printFooter: "Wygenerowane przez ApologistAI.com — Dla chwały Chrystusa",
  navDailyReading: "Czytanie dnia",
  dailyReadingTitle: "Czytania mszalne",
  dailyReadingLoading: "Ładowanie dzisiejszych czytań…",
  dailyReadingError: "Nie udało się załadować czytań. Odwiedź universalis.com.",
  dailyReadingSource: "Źródło: Universalis",
  navCommonQuestions: "Częste pytania",
  commonQuestionsTitle: "Częste pytania",
  commonQuestionsSub: "Kliknij pytanie, aby uzyskać natychmiastową odpowiedź.",
  bullets: [
    "Broń chrześcijaństwa Pismem i logiką",
    "Obalaj rzekome sprzeczności biblijne",
    "Analizuj słabości islamu, ateizmu i innych",
    "Wbudowane źródła apologetyczne i ministerialne",
  ],
  objections: [
    "Czy Bóg istnieje?",
    "Czy Biblia jest wiarygodna?",
    "Jak wyjaśnić Trójcę Świętą?",
    "Co z ewolucją?",
    "Jak dobry Bóg dopuszcza cierpienie?",
    "Co ze sprzecznościami w Biblii?",
    "Czy islam jest lepszą religią?",
    "Czy Jezus naprawdę zmartwychwstał?",
  ],
  starterQuestions: [
    "Czy Biblia jest historycznie wiarygodna?",
    "Czy islam obala chrześcijaństwo?",
    "Jak wyjaśnić Trójcę Świętą?",
    "Co ze sprzecznościami w Biblii?",
  ],
};

const LANGS: Partial<Record<Lang, Dict>> = { EN, PL };

function resolve(lang: Lang): Dict {
  return LANGS[lang] ?? EN;
}

type StringKeys = { [K in keyof Dict]: Dict[K] extends string ? K : never }[keyof Dict];
type ArrayKeys = { [K in keyof Dict]: Dict[K] extends string[] ? K : never }[keyof Dict];

export function t(lang: Lang, key: StringKeys): string {
  return (resolve(lang)[key] as string) ?? (EN[key] as string);
}

export function tArr(lang: Lang, key: ArrayKeys): string[] {
  return (resolve(lang)[key] as string[]) ?? (EN[key] as string[]);
}
