export type Lang = "EN" | "PL" | "ES";

interface Dict {
  // nav
  navHome: string;
  navMission: string;
  // hero
  heroLine1: string;
  heroLine2: string;
  heroSub: string;
  comingToMobile: string;
  comingSoon: string;
  verseOfDay: string;
  commonQuestionsLabel: string;
  tryItNow: string;
  buyMeCoffeeText: string;
  buyMeCoffeeBtn: string;
  // preview
  previewTagline: string;
  previewReady: string;
  previewHint: string;
  previewCta: string;
  previewPlaceholder: string;
  // chat
  chatHint: string;
  chatPlaceholder: string;
  responseMode: string;
  modeSimple: string;
  modeDetailed: string;
  modeChallenge: string;
  modeSimpleDesc: string;
  modeDetailedDesc: string;
  modeChallengeDesc: string;
  clearBtn: string;
  printBtn: string;
  errorMsg: string;
  // bubble
  saveBtn: string;
  copyBtn: string;
  copiedBtn: string;
  // about
  aboutTitle: string;
  aboutP1: string;
  aboutP2: string;
  feature1Icon: string;
  feature1Title: string;
  feature1Body: string;
  feature2Icon: string;
  feature2Title: string;
  feature2Body: string;
  feature3Icon: string;
  feature3Title: string;
  feature3Body: string;
  aboutQuote: string;
  aboutQuoteRef: string;
  // print
  printHeader: string;
  printYou: string;
  printBot: string;
  printFooter: string;
  // daily reading
  navDailyReading: string;
  dailyReadingTitle: string;
  dailyReadingLoading: string;
  dailyReadingError: string;
  dailyReadingSource: string;
  // common questions section
  navCommonQuestions: string;
  commonQuestionsTitle: string;
  commonQuestionsSub: string;
  // arrays
  bullets: string[];
  objections: string[];
  starterQuestions: string[];
}

const EN: Dict = {
  navHome: "Home",
  navMission: "Our Mission",
  heroLine1: "The Undefeated",
  heroLine2: "Christian Apologist",
  heroSub: "An AI assistant trained in Scripture, Church history, and comparative religion. Defend your faith, debunk objections, and explore the truth.",
  comingToMobile: "Coming to mobile",
  comingSoon: "Coming Soon",
  verseOfDay: "Verse of the Day",
  commonQuestionsLabel: "Common Questions",
  tryItNow: "Try it now →",
  buyMeCoffeeText: "If you'd like this project to continue and grow, feel free to buy me a coffee — I'm a one-man squad.",
  buyMeCoffeeBtn: "Buy me a coffee ☕",
  previewTagline: "Apologetics AI — Truth stands undefeated",
  previewReady: "Ready",
  previewHint: "Ask anything about Christianity — doctrine, objections, other religions, Biblical questions.",
  previewCta: "Click to start a conversation",
  previewPlaceholder: "Click to start chatting...",
  chatHint: "Ask anything about Christianity — doctrine, objections, other religions, Biblical questions.",
  chatPlaceholder: "Ask about Christianity, objections, or other religions...",
  responseMode: "Response mode:",
  modeSimple: "Simple",
  modeDetailed: "Detailed",
  modeChallenge: "⚔ Challenge",
  modeSimpleDesc: "Short, plain language answers",
  modeDetailedDesc: "In-depth with sources & rebuttals",
  modeChallengeDesc: "Face a skeptic — sharpen your faith",
  clearBtn: "Clear",
  printBtn: "Print",
  errorMsg: "Sorry, something went wrong. Please check your API key and try again.",
  saveBtn: "Save",
  copyBtn: "Copy",
  copiedBtn: "Copied!",
  aboutTitle: "Our Mission",
  aboutP1: "Apologist AI is a free ministry built to equip believers with sound, scripture-grounded answers to the hardest questions about Christianity. Whether you face doubts, skeptics, or sincere questions about the faith, this tool gives you access to centuries of apologetics, church history, and biblical scholarship — in plain language, at any hour.",
  aboutP2: "This is a passion project — one I always felt I had to build, as I genuinely love debating and deepening my knowledge of the faith. I believe every Christian should be able to give a reason for the hope within them (1 Peter 3:15). Not just pastors and scholars — every believer, every day. This project is offered freely, for the glory of Christ.",
  feature1Icon: "📖",
  feature1Title: "Scripture-First",
  feature1Body: "Every answer is grounded in the Word of God, with direct verse references.",
  feature2Icon: "🏛",
  feature2Title: "Historically Rooted",
  feature2Body: "Draws from Church Fathers, reformed theology, and 2,000 years of Christian thought.",
  feature3Icon: "⚔",
  feature3Title: "Battle-Tested",
  feature3Body: "Tackles Islam, atheism, cults, and modern skepticism head-on — confidently and charitably.",
  aboutQuote: "The light shines in the darkness, and the darkness has not overcome it.",
  aboutQuoteRef: "— John 1:5",
  printHeader: "✝ Apologist AI — Conversation",
  printYou: "You",
  printBot: "Apologist AI",
  printFooter: "Generated by ApologistAI.com — For the glory of Christ",
  navDailyReading: "Daily Reading",
  dailyReadingTitle: "Daily Mass Readings",
  dailyReadingLoading: "Loading today's readings…",
  dailyReadingError: "Could not load today's readings. Visit universalis.com for the full text.",
  dailyReadingSource: "Source: Universalis",
  navCommonQuestions: "Common Questions",
  commonQuestionsTitle: "Common Questions",
  commonQuestionsSub: "Tap any question for an instant answer from the AI.",
  bullets: [
    "Defend Christianity with Scripture & logic",
    "Debunk alleged contradictions",
    "Analyze flaws in Islam, atheism & more",
    "Scholar & ministry sources built in",
  ],
  objections: [
    "Does God exist?",
    "Is the Bible reliable?",
    "How do you explain the Trinity?",
    "What about evolution?",
    "How can a good God allow suffering?",
    "What about Biblical contradictions?",
    "Is Islam a better religion?",
    "Did Jesus really rise from the dead?",
  ],
  starterQuestions: [
    "Is the Bible historically reliable?",
    "Does Islam disprove Christianity?",
    "How do you explain the Trinity?",
    "What about Biblical contradictions?",
  ],
};

const PL: Dict = {
  navHome: "Strona główna",
  navMission: "Nasza misja",
  heroLine1: "Niezwyciężona",
  heroLine2: "Apologetyka Chrześcijańska",
  heroSub: "Asystent AI wyszkolony w Piśmie Świętym, historii Kościoła i religioznawstwie. Broń wiary, obalaj zarzuty i odkrywaj prawdę.",
  comingToMobile: "Wkrótce na telefon",
  comingSoon: "Wkrótce",
  verseOfDay: "Werset dnia",
  commonQuestionsLabel: "Częste pytania",
  tryItNow: "Wypróbuj →",
  buyMeCoffeeText: "Jeśli chcesz, żeby ten projekt się rozwijał, postaw mi kawę — działam sam.",
  buyMeCoffeeBtn: "Postaw mi kawę ☕",
  previewTagline: "AI Apologetyczne — Prawda jest niezwyciężona",
  previewReady: "Gotowe",
  previewHint: "Zadaj pytanie o chrześcijaństwo — doktrynę, zarzuty, inne religie lub Biblię.",
  previewCta: "Kliknij, aby rozpocząć rozmowę",
  previewPlaceholder: "Kliknij, aby zacząć...",
  chatHint: "Zadaj pytanie o chrześcijaństwo — doktrynę, zarzuty, inne religie lub Biblię.",
  chatPlaceholder: "Zapytaj o chrześcijaństwo, zarzuty lub inne religie...",
  responseMode: "Tryb odpowiedzi:",
  modeSimple: "Prosty",
  modeDetailed: "Szczegółowy",
  modeChallenge: "⚔ Wyzwanie",
  modeSimpleDesc: "Krótkie, przystępne odpowiedzi",
  modeDetailedDesc: "Szczegółowe odpowiedzi ze źródłami i kontrargumentami",
  modeChallengeDesc: "Zmierz się ze sceptykiem — wzmocnij wiarę",
  clearBtn: "Wyczyść",
  printBtn: "Drukuj",
  errorMsg: "Przepraszamy, coś poszło nie tak. Spróbuj ponownie.",
  saveBtn: "Zapisz",
  copyBtn: "Kopiuj",
  copiedBtn: "Skopiowano!",
  aboutTitle: "Nasza misja",
  aboutP1: "Apologist AI to bezpłatna posługa stworzona po to, by wyposażyć wierzących w rzetelne, zakorzenione w Piśmie Świętym odpowiedzi na najtrudniejsze pytania dotyczące chrześcijaństwa. Niezależnie od tego, czy mierzysz się z wątpliwościami, sceptykami czy szczerymi pytaniami o wiarę — to narzędzie daje ci dostęp do wieków apologetyki, historii Kościoła i biblistyki, w przystępnym języku, o każdej porze.",
  aboutP2: "To projekt z pasji — taki, który zawsze chciałem stworzyć, bo naprawdę lubię dyskutować i pogłębiać swoją wiedzę o wierze. Uważam, że każdy chrześcijanin powinien umieć uzasadnić nadzieję, która w nim jest (1 P 3,15). Nie tylko kapłani i uczeni — każdy wierzący, każdego dnia. Ten projekt jest oferowany bezpłatnie, dla chwały Chrystusa.",
  feature1Icon: "📖",
  feature1Title: "Biblia na pierwszym miejscu",
  feature1Body: "Każda odpowiedź zakorzeniona jest w Słowie Bożym, z bezpośrednimi odniesieniami do wersetów.",
  feature2Icon: "🏛",
  feature2Title: "Ugruntowane historycznie",
  feature2Body: "Czerpie od Ojców Kościoła, teologii i dwóch tysięcy lat myśli chrześcijańskiej.",
  feature3Icon: "⚔",
  feature3Title: "Sprawdzone w boju",
  feature3Body: "Odpowiada na wyzwania islamu, ateizmu, sekt i nowoczesnego sceptycyzmu — pewnie i z szacunkiem.",
  aboutQuote: "Światłość w ciemności świeci i ciemność jej nie ogarnęła.",
  aboutQuoteRef: "— J 1,5",
  printHeader: "✝ Apologist AI — Rozmowa",
  printYou: "Ty",
  printBot: "Apologist AI",
  printFooter: "Wygenerowane przez ApologistAI.com — Dla chwały Chrystusa",
  navDailyReading: "Czytania dnia",
  dailyReadingTitle: "Czytania mszalne",
  dailyReadingLoading: "Wczytywanie dzisiejszych czytań…",
  dailyReadingError: "Nie udało się wczytać czytań. Odwiedź universalis.com.",
  dailyReadingSource: "Źródło: Universalis",
  navCommonQuestions: "Częste pytania",
  commonQuestionsTitle: "Częste pytania",
  commonQuestionsSub: "Kliknij pytanie, by uzyskać natychmiastową odpowiedź od AI.",
  bullets: [
    "Broń chrześcijaństwa Pismem Świętym i logiką",
    "Obalaj rzekome sprzeczności biblijne",
    "Analizuj słabości islamu, ateizmu i innych",
    "Wbudowane źródła apologetyczne i kościelne",
  ],
  objections: [
    "Czy Bóg istnieje?",
    "Czy Biblia jest wiarygodna?",
    "Jak wytłumaczyć Trójcę Świętą?",
    "Co z teorią ewolucji?",
    "Jak dobry Bóg może dopuścić cierpienie?",
    "Co ze sprzecznościami w Biblii?",
    "Czy islam jest lepszą religią?",
    "Czy Jezus naprawdę zmartwychwstał?",
  ],
  starterQuestions: [
    "Czy Biblia jest historycznie wiarygodna?",
    "Czy islam obala chrześcijaństwo?",
    "Jak wytłumaczyć Trójcę Świętą?",
    "Co ze sprzecznościami w Biblii?",
  ],
};

const ES: Dict = {
  navHome: "Inicio",
  navMission: "Nuestra misión",
  heroLine1: "La Apologética",
  heroLine2: "Cristiana Invicta",
  heroSub: "Un asistente de IA entrenado en las Escrituras, la historia de la Iglesia y la religión comparada. Defiende tu fe, refuta objeciones y descubre la verdad.",
  comingToMobile: "Próximamente en móvil",
  comingSoon: "Próximamente",
  verseOfDay: "Versículo del día",
  commonQuestionsLabel: "Preguntas frecuentes",
  tryItNow: "Pruébalo ahora →",
  buyMeCoffeeText: "Si quieres que este proyecto continúe y crezca, invítame a un café — soy un equipo de una sola persona.",
  buyMeCoffeeBtn: "Invítame a un café ☕",
  previewTagline: "IA Apologética — La verdad permanece invicta",
  previewReady: "Listo",
  previewHint: "Pregunta sobre el cristianismo — doctrina, objeciones, otras religiones o la Biblia.",
  previewCta: "Haz clic para iniciar una conversación",
  previewPlaceholder: "Haz clic para comenzar...",
  chatHint: "Pregunta sobre el cristianismo — doctrina, objeciones, otras religiones o la Biblia.",
  chatPlaceholder: "Pregunta sobre el cristianismo, objeciones u otras religiones...",
  responseMode: "Modo de respuesta:",
  modeSimple: "Simple",
  modeDetailed: "Detallado",
  modeChallenge: "⚔ Desafío",
  modeSimpleDesc: "Respuestas cortas y claras",
  modeDetailedDesc: "Respuestas detalladas con fuentes y réplicas",
  modeChallengeDesc: "Enfréntate a un escéptico — fortalece tu fe",
  clearBtn: "Borrar",
  printBtn: "Imprimir",
  errorMsg: "Lo sentimos, algo salió mal. Por favor, inténtalo de nuevo.",
  saveBtn: "Guardar",
  copyBtn: "Copiar",
  copiedBtn: "¡Copiado!",
  aboutTitle: "Nuestra misión",
  aboutP1: "Apologist AI es un ministerio gratuito creado para equipar a los creyentes con respuestas sólidas, fundamentadas en las Escrituras, a las preguntas más difíciles sobre el cristianismo. Ya sea que enfrentes dudas, escépticos o preguntas sinceras sobre la fe, esta herramienta te da acceso a siglos de apologética, historia de la Iglesia y erudición bíblica, en lenguaje sencillo, a cualquier hora.",
  aboutP2: "Este es un proyecto nacido de la pasión — uno que siempre sentí que debía construir, porque realmente disfruto debatir y profundizar en el conocimiento de la fe. Creo que todo cristiano debe poder dar razón de la esperanza que hay en él (1 Pe 3,15). No solo pastores y estudiosos — cada creyente, cada día. Este proyecto se ofrece libremente, para la gloria de Cristo.",
  feature1Icon: "📖",
  feature1Title: "La Biblia primero",
  feature1Body: "Cada respuesta está fundamentada en la Palabra de Dios, con referencias directas a versículos.",
  feature2Icon: "🏛",
  feature2Title: "Arraigado en la historia",
  feature2Body: "Se nutre de los Padres de la Iglesia, la teología y dos mil años de pensamiento cristiano.",
  feature3Icon: "⚔",
  feature3Title: "Probado en el debate",
  feature3Body: "Responde a los desafíos del islam, el ateísmo, las sectas y el escepticismo moderno — con firmeza y caridad.",
  aboutQuote: "La luz brilla en las tinieblas, y las tinieblas no la vencieron.",
  aboutQuoteRef: "— Jn 1,5",
  printHeader: "✝ Apologist AI — Conversación",
  printYou: "Tú",
  printBot: "Apologist AI",
  printFooter: "Generado por ApologistAI.com — Para la gloria de Cristo",
  navDailyReading: "Lecturas del día",
  dailyReadingTitle: "Lecturas de la Misa diaria",
  dailyReadingLoading: "Cargando las lecturas de hoy…",
  dailyReadingError: "No se pudieron cargar las lecturas. Visita universalis.com.",
  dailyReadingSource: "Fuente: Universalis",
  navCommonQuestions: "Preguntas frecuentes",
  commonQuestionsTitle: "Preguntas frecuentes",
  commonQuestionsSub: "Toca cualquier pregunta para obtener una respuesta instantánea.",
  bullets: [
    "Defiende el cristianismo con las Escrituras y la lógica",
    "Refuta contradicciones bíblicas alegadas",
    "Analiza las debilidades del islam, el ateísmo y más",
    "Fuentes apologéticas y eclesiásticas integradas",
  ],
  objections: [
    "¿Existe Dios?",
    "¿Es confiable la Biblia?",
    "¿Cómo se explica la Trinidad?",
    "¿Qué hay de la evolución?",
    "¿Cómo permite el sufrimiento un Dios bueno?",
    "¿Qué hay de las contradicciones bíblicas?",
    "¿Es el islam una mejor religión?",
    "¿Resucitó realmente Jesús?",
  ],
  starterQuestions: [
    "¿Es la Biblia históricamente confiable?",
    "¿El islam refuta el cristianismo?",
    "¿Cómo se explica la Trinidad?",
    "¿Qué hay de las contradicciones bíblicas?",
  ],
};

const LANGS: Partial<Record<Lang, Dict>> = { EN, PL, ES };

function resolve(lang: Lang): Dict {
  return LANGS[lang] ?? EN;
}

type StringKeys = { [K in keyof Dict]: Dict[K] extends string ? K : never }[keyof Dict];
type ArrayKeys = { [K in keyof Dict]: Dict[K] extends string[] ? K : never }[keyof Dict];

export function t(lang: Lang, key: StringKeys): string {
  return (resolve(lang)[key] as string) ?? (EN[key] as string);
}

export function tArr(lang: Lang, key: ArrayKeys): string[] {
  return (resolve(lang)[key] as string[]) ?? (EN[key] as string[]);
}
