export type Lang = "EN" | "PL" | "ES" | "FR" | "DE";

interface Dict {
  // nav
  navHome: string;
  navMission: string;
  // hero
  heroLine1: string;
  heroLine2: string;
  heroSub: string;
  comingToMobile: string;
  comingSoon: string;
  verseOfDay: string;
  commonQuestionsLabel: string;
  tryItNow: string;
  buyMeCoffeeText: string;
  buyMeCoffeeBtn: string;
  // preview
  previewTagline: string;
  previewReady: string;
  previewHint: string;
  previewCta: string;
  previewPlaceholder: string;
  // chat
  chatHint: string;
  chatPlaceholder: string;
  responseMode: string;
  modeSimple: string;
  modeDetailed: string;
  modeChallenge: string;
  modeSimpleDesc: string;
  modeDetailedDesc: string;
  modeChallengeDesc: string;
  clearBtn: string;
  printBtn: string;
  errorMsg: string;
  // bubble
  saveBtn: string;
  copyBtn: string;
  copiedBtn: string;
  // about
  aboutTitle: string;
  aboutP1: string;
  aboutP2: string;
  feature1Icon: string;
  feature1Title: string;
  feature1Body: string;
  feature2Icon: string;
  feature2Title: string;
  feature2Body: string;
  feature3Icon: string;
  feature3Title: string;
  feature3Body: string;
  aboutQuote: string;
  aboutQuoteRef: string;
  // print
  printHeader: string;
  printYou: string;
  printBot: string;
  printFooter: string;
  // daily reading
  navDailyReading: string;
  dailyReadingTitle: string;
  dailyReadingLoading: string;
  dailyReadingError: string;
  dailyReadingSource: string;
  // common questions section
  navCommonQuestions: string;
  commonQuestionsTitle: string;
  commonQuestionsSub: string;
  // arrays
  bullets: string[];
  objections: string[];
  starterQuestions: string[];
}

const EN: Dict = {
  navHome: "Home",
  navMission: "Our Mission",
  heroLine1: "The Undefeated",
  heroLine2: "Christian Apologist",
  heroSub: "An AI assistant trained in Scripture, Church history, and comparative religion. Defend your faith, debunk objections, and explore the truth.",
  comingToMobile: "Coming to mobile",
  comingSoon: "Coming Soon",
  verseOfDay: "Verse of the Day",
  commonQuestionsLabel: "Common Questions",
  tryItNow: "Try it now →",
  buyMeCoffeeText: "If you'd like this project to continue and grow, feel free to buy me a coffee — I'm a one-man squad.",
  buyMeCoffeeBtn: "Buy me a coffee ☕",
  previewTagline: "Apologetics AI — Truth stands undefeated",
  previewReady: "Ready",
  previewHint: "Ask anything about Christianity — doctrine, objections, other religions, Biblical questions.",
  previewCta: "Click to start a conversation",
  previewPlaceholder: "Click to start chatting...",
  chatHint: "Ask anything about Christianity — doctrine, objections, other religions, Biblical questions.",
  chatPlaceholder: "Ask about Christianity, objections, or other religions...",
  responseMode: "Response mode:",
  modeSimple: "Simple",
  modeDetailed: "Detailed",
  modeChallenge: "⚔ Challenge",
  modeSimpleDesc: "Short, plain language answers",
  modeDetailedDesc: "In-depth with sources & rebuttals",
  modeChallengeDesc: "Face a skeptic — sharpen your faith",
  clearBtn: "Clear",
  printBtn: "Print",
  errorMsg: "Sorry, something went wrong. Please check your API key and try again.",
  saveBtn: "Save",
  copyBtn: "Copy",
  copiedBtn: "Copied!",
  aboutTitle: "Our Mission",
  aboutP1: "Apologist AI is a free ministry built to equip believers with sound, scripture-grounded answers to the hardest questions about Christianity. Whether you face doubts, skeptics, or sincere questions about the faith, this tool gives you access to centuries of apologetics, church history, and biblical scholarship — in plain language, at any hour.",
  aboutP2: "This is a passion project — one I always felt I had to build, as I genuinely love debating and deepening my knowledge of the faith. I believe every Christian should be able to give a reason for the hope within them (1 Peter 3:15). Not just pastors and scholars — every believer, every day. This project is offered freely, for the glory of Christ.",
  feature1Icon: "📖",
  feature1Title: "Scripture-First",
  feature1Body: "Every answer is grounded in the Word of God, with direct verse references.",
  feature2Icon: "🏛",
  feature2Title: "Historically Rooted",
  feature2Body: "Draws from Church Fathers, reformed theology, and 2,000 years of Christian thought.",
  feature3Icon: "⚔",
  feature3Title: "Battle-Tested",
  feature3Body: "Tackles Islam, atheism, cults, and modern skepticism head-on — confidently and charitably.",
  aboutQuote: "The light shines in the darkness, and the darkness has not overcome it.",
  aboutQuoteRef: "— John 1:5",
  printHeader: "✝ Apologist AI — Conversation",
  printYou: "You",
  printBot: "Apologist AI",
  printFooter: "Generated by ApologistAI.com — For the glory of Christ",
  navDailyReading: "Daily Reading",
  dailyReadingTitle: "Daily Mass Readings",
  dailyReadingLoading: "Loading today's readings…",
  dailyReadingError: "Could not load today's readings. Visit universalis.com for the full text.",
  dailyReadingSource: "Source: Universalis",
  navCommonQuestions: "Common Questions",
  commonQuestionsTitle: "Common Questions",
  commonQuestionsSub: "Tap any question for an instant answer from the AI.",
  bullets: [
    "Defend Christianity with Scripture & logic",
    "Debunk alleged contradictions",
    "Analyze flaws in Islam, atheism & more",
    "Scholar & ministry sources built in",
  ],
  objections: [
    "Does God exist?",
    "Is the Bible reliable?",
    "How do you explain the Trinity?",
    "What about evolution?",
    "How can a good God allow suffering?",
    "What about Biblical contradictions?",
    "Is Islam a better religion?",
    "Did Jesus really rise from the dead?",
  ],
  starterQuestions: [
    "Is the Bible historically reliable?",
    "Does Islam disprove Christianity?",
    "How do you explain the Trinity?",
    "What about Biblical contradictions?",
  ],
};

const PL: Dict = {
  navHome: "Strona główna",
  navMission: "Nasza misja",
  heroLine1: "Niezwyciężona",
  heroLine2: "Apologetyka Chrześcijańska",
  heroSub: "Asystent AI wyszkolony w Piśmie Świętym, historii Kościoła i religioznawstwie. Broń wiary, obalaj zarzuty i odkrywaj prawdę.",
  comingToMobile: "Wkrótce na telefon",
  comingSoon: "Wkrótce",
  verseOfDay: "Werset dnia",
  commonQuestionsLabel: "Częste pytania",
  tryItNow: "Wypróbuj →",
  buyMeCoffeeText: "Jeśli chcesz, żeby ten projekt się rozwijał, postaw mi kawę — działam sam.",
  buyMeCoffeeBtn: "Postaw mi kawę ☕",
  previewTagline: "AI Apologetyczne — Prawda jest niezwyciężona",
  previewReady: "Gotowe",
  previewHint: "Zadaj pytanie o chrześcijaństwo — doktrynę, zarzuty, inne religie lub Biblię.",
  previewCta: "Kliknij, aby rozpocząć rozmowę",
  previewPlaceholder: "Kliknij, aby zacząć...",
  chatHint: "Zadaj pytanie o chrześcijaństwo — doktrynę, zarzuty, inne religie lub Biblię.",
  chatPlaceholder: "Zapytaj o chrześcijaństwo, zarzuty lub inne religie...",
  responseMode: "Tryb odpowiedzi:",
  modeSimple: "Prosty",
  modeDetailed: "Szczegółowy",
  modeChallenge: "⚔ Wyzwanie",
  modeSimpleDesc: "Krótkie, przystępne odpowiedzi",
  modeDetailedDesc: "Szczegółowe odpowiedzi ze źródłami i kontrargumentami",
  modeChallengeDesc: "Zmierz się ze sceptykiem — wzmocnij wiarę",
  clearBtn: "Wyczyść",
  printBtn: "Drukuj",
  errorMsg: "Przepraszamy, coś poszło nie tak. Spróbuj ponownie.",
  saveBtn: "Zapisz",
  copyBtn: "Kopiuj",
  copiedBtn: "Skopiowano!",
  aboutTitle: "Nasza misja",
  aboutP1: "Apologist AI to bezpłatna posługa stworzona po to, by wyposażyć wierzących w rzetelne, zakorzenione w Piśmie Świętym odpowiedzi na najtrudniejsze pytania dotyczące chrześcijaństwa. Niezależnie od tego, czy mierzysz się z wątpliwościami, sceptykami czy szczerymi pytaniami o wiarę — to narzędzie daje ci dostęp do wieków apologetyki, historii Kościoła i biblistyki, w przystępnym języku, o każdej porze.",
  aboutP2: "To projekt z pasji — taki, który zawsze chciałem stworzyć, bo naprawdę lubię dyskutować i pogłębiać swoją wiedzę o wierze. Uważam, że każdy chrześcijanin powinien umieć uzasadnić nadzieję, która w nim jest (1 P 3,15). Nie tylko kapłani i uczeni — każdy wierzący, każdego dnia. Ten projekt jest oferowany bezpłatnie, dla chwały Chrystusa.",
  feature1Icon: "📖",
  feature1Title: "Biblia na pierwszym miejscu",
  feature1Body: "Każda odpowiedź zakorzeniona jest w Słowie Bożym, z bezpośrednimi odniesieniami do wersetów.",
  feature2Icon: "🏛",
  feature2Title: "Ugruntowane historycznie",
  feature2Body: "Czerpie od Ojców Kościoła, teologii i dwóch tysięcy lat myśli chrześcijańskiej.",
  feature3Icon: "⚔",
  feature3Title: "Sprawdzone w boju",
  feature3Body: "Odpowiada na wyzwania islamu, ateizmu, sekt i nowoczesnego sceptycyzmu — pewnie i z szacunkiem.",
  aboutQuote: "Światłość w ciemności świeci i ciemność jej nie ogarnęła.",
  aboutQuoteRef: "— J 1,5",
  printHeader: "✝ Apologist AI — Rozmowa",
  printYou: "Ty",
  printBot: "Apologist AI",
  printFooter: "Wygenerowane przez ApologistAI.com — Dla chwały Chrystusa",
  navDailyReading: "Czytania dnia",
  dailyReadingTitle: "Czytania mszalne",
  dailyReadingLoading: "Wczytywanie dzisiejszych czytań…",
  dailyReadingError: "Nie udało się wczytać czytań. Odwiedź universalis.com.",
  dailyReadingSource: "Źródło: Universalis",
  navCommonQuestions: "Częste pytania",
  commonQuestionsTitle: "Częste pytania",
  commonQuestionsSub: "Kliknij pytanie, by uzyskać natychmiastową odpowiedź od AI.",
  bullets: [
    "Broń chrześcijaństwa Pismem Świętym i logiką",
    "Obalaj rzekome sprzeczności biblijne",
    "Analizuj słabości islamu, ateizmu i innych",
    "Wbudowane źródła apologetyczne i kościelne",
  ],
  objections: [
    "Czy Bóg istnieje?",
    "Czy Biblia jest wiarygodna?",
    "Jak wytłumaczyć Trójcę Świętą?",
    "Co z teorią ewolucji?",
    "Jak dobry Bóg może dopuścić cierpienie?",
    "Co ze sprzecznościami w Biblii?",
    "Czy islam jest lepszą religią?",
    "Czy Jezus naprawdę zmartwychwstał?",
  ],
  starterQuestions: [
    "Czy Biblia jest historycznie wiarygodna?",
    "Czy islam obala chrześcijaństwo?",
    "Jak wytłumaczyć Trójcę Świętą?",
    "Co ze sprzecznościami w Biblii?",
  ],
};

const ES: Dict = {
  navHome: "Inicio",
  navMission: "Nuestra misión",
  heroLine1: "La Apologética",
  heroLine2: "Cristiana Invicta",
  heroSub: "Un asistente de IA entrenado en las Escrituras, la historia de la Iglesia y la religión comparada. Defiende tu fe, refuta objeciones y descubre la verdad.",
  comingToMobile: "Próximamente en móvil",
  comingSoon: "Próximamente",
  verseOfDay: "Versículo del día",
  commonQuestionsLabel: "Preguntas frecuentes",
  tryItNow: "Pruébalo ahora →",
  buyMeCoffeeText: "Si quieres que este proyecto continúe y crezca, invítame a un café — soy un equipo de una sola persona.",
  buyMeCoffeeBtn: "Invítame a un café ☕",
  previewTagline: "IA Apologética — La verdad permanece invicta",
  previewReady: "Listo",
  previewHint: "Pregunta sobre el cristianismo — doctrina, objeciones, otras religiones o la Biblia.",
  previewCta: "Haz clic para iniciar una conversación",
  previewPlaceholder: "Haz clic para comenzar...",
  chatHint: "Pregunta sobre el cristianismo — doctrina, objeciones, otras religiones o la Biblia.",
  chatPlaceholder: "Pregunta sobre el cristianismo, objeciones u otras religiones...",
  responseMode: "Modo de respuesta:",
  modeSimple: "Simple",
  modeDetailed: "Detallado",
  modeChallenge: "⚔ Desafío",
  modeSimpleDesc: "Respuestas cortas y claras",
  modeDetailedDesc: "Respuestas detalladas con fuentes y réplicas",
  modeChallengeDesc: "Enfréntate a un escéptico — fortalece tu fe",
  clearBtn: "Borrar",
  printBtn: "Imprimir",
  errorMsg: "Lo sentimos, algo salió mal. Por favor, inténtalo de nuevo.",
  saveBtn: "Guardar",
  copyBtn: "Copiar",
  copiedBtn: "¡Copiado!",
  aboutTitle: "Nuestra misión",
  aboutP1: "Apologist AI es un ministerio gratuito creado para equipar a los creyentes con respuestas sólidas, fundamentadas en las Escrituras, a las preguntas más difíciles sobre el cristianismo. Ya sea que enfrentes dudas, escépticos o preguntas sinceras sobre la fe, esta herramienta te da acceso a siglos de apologética, historia de la Iglesia y erudición bíblica, en lenguaje sencillo, a cualquier hora.",
  aboutP2: "Este es un proyecto nacido de la pasión — uno que siempre sentí que debía construir, porque realmente disfruto debatir y profundizar en el conocimiento de la fe. Creo que todo cristiano debe poder dar razón de la esperanza que hay en él (1 Pe 3,15). No solo pastores y estudiosos — cada creyente, cada día. Este proyecto se ofrece libremente, para la gloria de Cristo.",
  feature1Icon: "📖",
  feature1Title: "La Biblia primero",
  feature1Body: "Cada respuesta está fundamentada en la Palabra de Dios, con referencias directas a versículos.",
  feature2Icon: "🏛",
  feature2Title: "Arraigado en la historia",
  feature2Body: "Se nutre de los Padres de la Iglesia, la teología y dos mil años de pensamiento cristiano.",
  feature3Icon: "⚔",
  feature3Title: "Probado en el debate",
  feature3Body: "Responde a los desafíos del islam, el ateísmo, las sectas y el escepticismo moderno — con firmeza y caridad.",
  aboutQuote: "La luz brilla en las tinieblas, y las tinieblas no la vencieron.",
  aboutQuoteRef: "— Jn 1,5",
  printHeader: "✝ Apologist AI — Conversación",
  printYou: "Tú",
  printBot: "Apologist AI",
  printFooter: "Generado por ApologistAI.com — Para la gloria de Cristo",
  navDailyReading: "Lecturas del día",
  dailyReadingTitle: "Lecturas de la Misa diaria",
  dailyReadingLoading: "Cargando las lecturas de hoy…",
  dailyReadingError: "No se pudieron cargar las lecturas. Visita universalis.com.",
  dailyReadingSource: "Fuente: Universalis",
  navCommonQuestions: "Preguntas frecuentes",
  commonQuestionsTitle: "Preguntas frecuentes",
  commonQuestionsSub: "Toca cualquier pregunta para obtener una respuesta instantánea.",
  bullets: [
    "Defiende el cristianismo con las Escrituras y la lógica",
    "Refuta contradicciones bíblicas alegadas",
    "Analiza las debilidades del islam, el ateísmo y más",
    "Fuentes apologéticas y eclesiásticas integradas",
  ],
  objections: [
    "¿Existe Dios?",
    "¿Es confiable la Biblia?",
    "¿Cómo se explica la Trinidad?",
    "¿Qué hay de la evolución?",
    "¿Cómo permite el sufrimiento un Dios bueno?",
    "¿Qué hay de las contradicciones bíblicas?",
    "¿Es el islam una mejor religión?",
    "¿Resucitó realmente Jesús?",
  ],
  starterQuestions: [
    "¿Es la Biblia históricamente confiable?",
    "¿El islam refuta el cristianismo?",
    "¿Cómo se explica la Trinidad?",
    "¿Qué hay de las contradicciones bíblicas?",
  ],
};

const FR: Dict = {
  navHome: "Accueil",
  navMission: "Notre mission",
  heroLine1: "L'Apologétique",
  heroLine2: "Chrétienne Invincible",
  heroSub: "Un assistant IA formé aux Écritures, à l'histoire de l'Église et aux religions comparées. Défends ta foi, réfute les objections et découvre la vérité.",
  comingToMobile: "Bientôt sur mobile",
  comingSoon: "Bientôt disponible",
  verseOfDay: "Verset du jour",
  commonQuestionsLabel: "Questions fréquentes",
  tryItNow: "Essaie maintenant →",
  buyMeCoffeeText: "Si tu veux que ce projet continue de grandir, offre-moi un café — je travaille seul.",
  buyMeCoffeeBtn: "Offrir un café ☕",
  previewTagline: "IA Apologétique — La vérité demeure invincible",
  previewReady: "Prêt",
  previewHint: "Pose une question sur le christianisme — doctrine, objections, autres religions ou la Bible.",
  previewCta: "Clique pour démarrer une conversation",
  previewPlaceholder: "Clique pour commencer...",
  chatHint: "Pose une question sur le christianisme — doctrine, objections, autres religions ou la Bible.",
  chatPlaceholder: "Pose une question sur le christianisme, les objections ou d'autres religions...",
  responseMode: "Mode de réponse :",
  modeSimple: "Simple",
  modeDetailed: "Détaillé",
  modeChallenge: "⚔ Défi",
  modeSimpleDesc: "Réponses courtes et claires",
  modeDetailedDesc: "Réponses détaillées avec sources et réfutations",
  modeChallengeDesc: "Affronte un sceptique — renforce ta foi",
  clearBtn: "Effacer",
  printBtn: "Imprimer",
  errorMsg: "Désolé, quelque chose s'est mal passé. Veuillez réessayer.",
  saveBtn: "Enregistrer",
  copyBtn: "Copier",
  copiedBtn: "Copié !",
  aboutTitle: "Notre mission",
  aboutP1: "Apologist AI est un ministère gratuit conçu pour équiper les croyants de réponses solides, fondées sur les Écritures, aux questions les plus difficiles sur le christianisme. Que tu fasses face à des doutes, des sceptiques ou des questions sincères sur la foi, cet outil te donne accès à des siècles d'apologétique, d'histoire de l'Église et d'érudition biblique — en langage simple, à toute heure.",
  aboutP2: "C'est un projet de passion — celui que j'ai toujours voulu construire, car j'aime vraiment débattre et approfondir ma connaissance de la foi. Je crois que tout chrétien doit pouvoir rendre compte de l'espérance qui est en lui (1 P 3,15). Pas seulement les pasteurs et les théologiens — chaque croyant, chaque jour. Ce projet est offert gratuitement, pour la gloire du Christ.",
  feature1Icon: "📖",
  feature1Title: "La Bible en premier",
  feature1Body: "Chaque réponse est fondée sur la Parole de Dieu, avec des références directes aux versets.",
  feature2Icon: "🏛",
  feature2Title: "Ancré dans l'histoire",
  feature2Body: "S'appuie sur les Pères de l'Église, la théologie et deux mille ans de pensée chrétienne.",
  feature3Icon: "⚔",
  feature3Title: "Éprouvé au débat",
  feature3Body: "Répond aux défis de l'islam, de l'athéisme, des sectes et du scepticisme moderne — avec fermeté et charité.",
  aboutQuote: "La lumière luit dans les ténèbres, et les ténèbres ne l'ont point reçue.",
  aboutQuoteRef: "— Jn 1,5",
  printHeader: "✝ Apologist AI — Conversation",
  printYou: "Vous",
  printBot: "Apologist AI",
  printFooter: "Généré par ApologistAI.com — Pour la gloire du Christ",
  navDailyReading: "Lectures du jour",
  dailyReadingTitle: "Lectures de la Messe quotidienne",
  dailyReadingLoading: "Chargement des lectures du jour…",
  dailyReadingError: "Impossible de charger les lectures. Visitez universalis.com.",
  dailyReadingSource: "Source : Universalis",
  navCommonQuestions: "Questions fréquentes",
  commonQuestionsTitle: "Questions fréquentes",
  commonQuestionsSub: "Clique sur une question pour obtenir une réponse instantanée.",
  bullets: [
    "Défends le christianisme avec les Écritures et la logique",
    "Réfute les prétendues contradictions bibliques",
    "Analyse les failles de l'islam, de l'athéisme et plus encore",
    "Sources apologétiques et ecclésiastiques intégrées",
  ],
  objections: [
    "Dieu existe-t-il ?",
    "La Bible est-elle fiable ?",
    "Comment expliquer la Trinité ?",
    "Qu'en est-il de l'évolution ?",
    "Comment un bon Dieu permet-il la souffrance ?",
    "Qu'en est-il des contradictions bibliques ?",
    "L'islam est-il une meilleure religion ?",
    "Jésus est-il vraiment ressuscité ?",
  ],
  starterQuestions: [
    "La Bible est-elle historiquement fiable ?",
    "L'islam réfute-t-il le christianisme ?",
    "Comment expliquer la Trinité ?",
    "Qu'en est-il des contradictions bibliques ?",
  ],
};

const DE: Dict = {
  navHome: "Startseite",
  navMission: "Unsere Mission",
  heroLine1: "Die Unbesiegte",
  heroLine2: "Christliche Apologetik",
  heroSub: "Ein KI-Assistent, trainiert in der Heiligen Schrift, Kirchengeschichte und Religionsvergleich. Verteidige deinen Glauben, widerlege Einwände und entdecke die Wahrheit.",
  comingToMobile: "Bald auf dem Handy",
  comingSoon: "Demnächst",
  verseOfDay: "Tagesvers",
  commonQuestionsLabel: "Häufige Fragen",
  tryItNow: "Jetzt ausprobieren →",
  buyMeCoffeeText: "Wenn du möchtest, dass dieses Projekt weiter wächst, spendier mir einen Kaffee — ich arbeite alleine.",
  buyMeCoffeeBtn: "Kaffee spendieren ☕",
  previewTagline: "Apologetik-KI — Die Wahrheit bleibt unbestritten",
  previewReady: "Bereit",
  previewHint: "Stelle eine Frage zum Christentum — Lehre, Einwände, andere Religionen oder die Bibel.",
  previewCta: "Klicke, um ein Gespräch zu beginnen",
  previewPlaceholder: "Klicke, um zu beginnen...",
  chatHint: "Stelle eine Frage zum Christentum — Lehre, Einwände, andere Religionen oder die Bibel.",
  chatPlaceholder: "Frage über das Christentum, Einwände oder andere Religionen...",
  responseMode: "Antwortmodus:",
  modeSimple: "Einfach",
  modeDetailed: "Ausführlich",
  modeChallenge: "⚔ Herausforderung",
  modeSimpleDesc: "Kurze, klare Antworten",
  modeDetailedDesc: "Ausführliche Antworten mit Quellen und Widerlegungen",
  modeChallengeDesc: "Stell dich einem Skeptiker — stärke deinen Glauben",
  clearBtn: "Löschen",
  printBtn: "Drucken",
  errorMsg: "Entschuldigung, etwas ist schiefgelaufen. Bitte versuche es erneut.",
  saveBtn: "Speichern",
  copyBtn: "Kopieren",
  copiedBtn: "Kopiert!",
  aboutTitle: "Unsere Mission",
  aboutP1: "Apologist AI ist ein kostenloses Ministerium, das Gläubigen fundierte, schriftbasierte Antworten auf die schwierigsten Fragen zum Christentum geben soll. Ob du Zweifeln, Skeptikern oder aufrichtigen Glaubensfragen begegnest — dieses Werkzeug gibt dir Zugang zu Jahrhunderten der Apologetik, Kirchengeschichte und Bibelwissenschaft, in verständlicher Sprache, zu jeder Stunde.",
  aboutP2: "Dies ist ein Leidenschaftsprojekt — eines, das ich immer bauen wollte, weil ich es wirklich liebe, zu diskutieren und mein Glaubenswissen zu vertiefen. Ich glaube, dass jeder Christ in der Lage sein sollte, Rechenschaft über die Hoffnung in ihm abzulegen (1 Petr 3,15). Nicht nur Pastoren und Theologen — jeder Gläubige, jeden Tag. Dieses Projekt wird kostenlos angeboten, zur Ehre Christi.",
  feature1Icon: "📖",
  feature1Title: "Die Bibel zuerst",
  feature1Body: "Jede Antwort gründet auf dem Wort Gottes, mit direkten Verweisen auf Bibelverse.",
  feature2Icon: "🏛",
  feature2Title: "Historisch verwurzelt",
  feature2Body: "Schöpft aus den Kirchenvätern, der Theologie und zweitausend Jahren christlichen Denkens.",
  feature3Icon: "⚔",
  feature3Title: "Im Streit bewährt",
  feature3Body: "Begegnet den Herausforderungen des Islam, Atheismus, Sekten und modernen Skeptizismus — fest und respektvoll.",
  aboutQuote: "Das Licht scheint in der Finsternis, und die Finsternis hat es nicht erfasst.",
  aboutQuoteRef: "— Joh 1,5",
  printHeader: "✝ Apologist AI — Gespräch",
  printYou: "Du",
  printBot: "Apologist AI",
  printFooter: "Erstellt von ApologistAI.com — Zur Ehre Christi",
  navDailyReading: "Tageslesungen",
  dailyReadingTitle: "Tägliche Messlesungen",
  dailyReadingLoading: "Heutige Lesungen werden geladen…",
  dailyReadingError: "Die Lesungen konnten nicht geladen werden. Besuche universalis.com.",
  dailyReadingSource: "Quelle: Universalis",
  navCommonQuestions: "Häufige Fragen",
  commonQuestionsTitle: "Häufige Fragen",
  commonQuestionsSub: "Klicke auf eine Frage für eine sofortige Antwort.",
  bullets: [
    "Verteidige das Christentum mit Schrift und Logik",
    "Widerlege angebliche biblische Widersprüche",
    "Analysiere Schwachstellen des Islam, Atheismus u. v. m.",
    "Apologetische und kirchliche Quellen integriert",
  ],
  objections: [
    "Gibt es Gott?",
    "Ist die Bibel zuverlässig?",
    "Wie erklärt man die Dreifaltigkeit?",
    "Was ist mit der Evolution?",
    "Wie kann ein guter Gott Leiden zulassen?",
    "Was ist mit den Widersprüchen in der Bibel?",
    "Ist der Islam eine bessere Religion?",
    "Ist Jesus wirklich auferstanden?",
  ],
  starterQuestions: [
    "Ist die Bibel historisch zuverlässig?",
    "Widerlegt der Islam das Christentum?",
    "Wie erklärt man die Dreifaltigkeit?",
    "Was ist mit den Widersprüchen in der Bibel?",
  ],
};

const LANGS: Partial<Record<Lang, Dict>> = { EN, PL, ES, FR, DE };

function resolve(lang: Lang): Dict {
  return LANGS[lang] ?? EN;
}

type StringKeys = { [K in keyof Dict]: Dict[K] extends string ? K : never }[keyof Dict];
type ArrayKeys = { [K in keyof Dict]: Dict[K] extends string[] ? K : never }[keyof Dict];

export function t(lang: Lang, key: StringKeys): string {
  return (resolve(lang)[key] as string) ?? (EN[key] as string);
}

export function tArr(lang: Lang, key: ArrayKeys): string[] {
  return (resolve(lang)[key] as string[]) ?? (EN[key] as string[]);
}
